[package]
name = "polkabtc-telemetry-types"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }